### ISSUE TITLE
Not starting on Arch Linux

### ISSUE THREAD

**Issue by carnager** [pdaddyo/soundbounce-v2#29]
```
carnager@caprica ~/soundbounce-v2 > npm run-script dev

> soundbounce-v2@0.1.0 dev /home/carnager/soundbounce-v2
> better-npm-run dev

running better-npm-run in /home/carnager/soundbounce-v2
Executing script: dev

to be executed: nodemon --exec node ./node_modules/babel-cli/bin/babel-node.js client-bin/server 
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./node_modules/babel-cli/bin/babel-node.js client-bin/server`
  soundbounce:config Create configuration. +0ms
  soundbounce:config Apply environment overrides for NODE_ENV "development". +1ms
  soundbounce:webpack:config Create configuration. +402ms
  soundbounce:webpack:config Enable plugins for live development (HMR, NoErrors). +0ms
  soundbounce:server Begin server init... +312ms
  soundbounce:data:schema Syncing database schema (sequelize.sync)... +1ms
  soundbounce:server DEV MODE - Enabling webpack dev and HMR middleware +20ms
  soundbounce:data:schema Error syncing database :connect ECONNREFUSED 127.0.0.1:5432 +90ms
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at /home/carnager/soundbounce-v2/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:98:20
    at Connection.<anonymous> (/home/carnager/soundbounce-v2/node_modules/pg/lib/client.js:186:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/carnager/soundbounce-v2/node_modules/pg/lib/connection.js:86:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at ConnectionManager.connect (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:89:10)
    at ConnectionManager.<anonymous> (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
From previous event:
    at Promise.then (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/promise.js:21:17)
    at Model.sync (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/model.js:993:6)
    at /home/carnager/soundbounce-v2/node_modules/sequelize/lib/sequelize.js:1014:20
From previous event:
    at Function.each (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/promise.js:21:17)
    at /home/carnager/soundbounce-v2/node_modules/sequelize/lib/sequelize.js:1013:20
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Promise.then (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/promise.js:21:17)
    at Sequelize.sync (/home/carnager/soundbounce-v2/node_modules/sequelize/lib/sequelize.js:1000:6)
    at syncDatabaseSchema (/home/carnager/soundbounce-v2/server/soundbounce/data/schema.js:101:12)
    at Server.init (/home/carnager/soundbounce-v2/server/soundbounce/app/Server.js:27:3)
    at Object.<anonymous> (/home/carnager/soundbounce-v2/server/main.js:22:13)
    at Module._compile (module.js:571:32)
    at loader (/home/carnager/soundbounce-v2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/carnager/soundbounce-v2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/carnager/soundbounce-v2/client-bin/server.js:2:1)
    at Module._compile (module.js:571:32)
    at loader (/home/carnager/soundbounce-v2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/carnager/soundbounce-v2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

webpack built 3a02dd5a89d70bb43998 in 6376ms
Hash: 3a02dd5a89d70bb43998
Version: webpack 1.12.9
Time: 6376ms
                                              Asset       Size  Chunks             Chunk Names
              client/js/app.3a02dd5a89d70bb43998.js     3.7 MB       0  [emitted]  app
               client/fonts/helveticaneue-thin.woff    60.9 kB          [emitted]  
            client/fonts/helveticaneue-regular.woff    48.8 kB          [emitted]  
               client/fonts/helveticaneue-bold.woff     219 kB          [emitted]  
client/img/img-f17243e150fdd24a2cd3d3c67a17bb70.png    88.9 kB          [emitted]  
              client/fonts/helveticaneue-light.woff    57.8 kB          [emitted]  
           client/js/vendor.3a02dd5a89d70bb43998.js     414 kB       1  [emitted]  vendor
          client/js/app.3a02dd5a89d70bb43998.js.map    4.36 MB       0  [emitted]  app
       client/js/vendor.3a02dd5a89d70bb43998.js.map     496 kB       1  [emitted]  vendor
                                        favicon.ico     1.3 kB          [emitted]  
                                         index.html  531 bytes          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  576 kB       0       
webpack: Compiled successfully.
```

And then it's stuck and nothing seems to be listening.

**Comment by pdaddyo** [comment]
> Error syncing database :connect ECONNREFUSED 127.0.0.1:5432

Your app is failing to connect to postgres. Ensure you have postgres 9.6+ installed, and enter your correct db connection string into the secrets file.
